SELECT B.ANIMAL_ID,B.NAME FROM ANIMAL_OUTS B LEFT JOIN ANIMAL_INS A
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.ANIMAL_ID IS NULL
ORDER BY B.ANIMAL_ID


# SELECT O.ANIMAL_ID, O.NAME FROM ANIMAL_INS I
# RIGHT JOIN ANIMAL_OUTS O
# ON O.ANIMAL_ID = I.ANIMAL_ID
# WHERE I.ANIMAL_ID IS NULL
# ORDER BY O.ANIMAL_ID