-- 코드를 입력하세요
SELECT A.MCDP_CD AS '진료과코드', COUNT(A.MCDP_CD) AS '5월예약건수' FROM APPOINTMENT A
WHERE DATE_FORMAT(A.APNT_YMD,'%m') LIKE '05'
GROUP BY A.MCDP_CD
ORDER BY COUNT(A.MCDP_CD), A.MCDP_CD

# SELECT * FROM APPOINTMENT A